# **Python Tutorial 

# - General Python3:
* [Official site](https://www.python.org/)
* [documentation](https://docs.python.org/3.9/contents.html)

# - Python exercices:
* [w3resource](https://www.w3resource.com/python-exercises/)

# - And... "googling"!


<figure>
<center>
<img src='https://drive.google.com/uc?export=view&id=114xYB3NpE01oQ8j3X1d6s0WDBi0V432B' alt="Chord chart piano" height="400"> 
</center>
</figure>


*Credits to Justin Johnson, Volodymyr Kuleshov and Isaac Caswell.*

# Introduction

Python is a great general-purpose programming language on its own, but with the help of a few popular libraries (`numpy`, `scipy`, `matplotlib`) it becomes a powerful environment for scientific computing.

In this tutorial, we will cover:

* **Basic Python**: Basic data types (Containers, Lists, Dictionaries, Sets, Tuples), Functions, Classes
* **Numpy**: Arrays, Array indexing, Datatypes, Array math, Broadcasting
* **Matplotlib**: Plotting, Subplots, Images

In [47]:
!python --version
!uname -a

Python 3.11.5


"uname" non � riconosciuto come comando interno o esterno,
 un programma eseguibile o un file batch.


# Basics of Python

Python is a **high-level, dynamically typed multiparadigm programming language**. Python code is often said to be almost **like pseudocode**, since it allows you to express very powerful ideas in very few lines of code while being very readable. As an **example**, here is an implementation of the classic quicksort algorithm in Python:

In [48]:
def quicksort(arr):
  if len(arr) <= 1:
    return arr
  pivot = arr[len(arr) // 2]
  left = [x for x in arr if x < pivot]
  middle = [x for x in arr if x == pivot]
  right = [x for x in arr if x > pivot]
  return quicksort(left) + middle + quicksort(right)

print(quicksort([3,6,8,10,1,2,1]))
print(quicksort(['P','Y','T','H','O','N']))

[1, 1, 2, 3, 6, 8, 10]
['H', 'N', 'O', 'P', 'T', 'Y']


Quick sort in C (notice the difference!):

```
void swap(int* a, int* b) 
{ 
    int t = *a; 
    *a = *b; 
    *b = t; 
} 

int partition (int arr[], int low, int high) 
{ 
    int pivot = arr[high]; 
    int i = (low - 1); 
    for (int j = low; j <= high - 1; j++) 
    { 
        if (arr[j] < pivot) 
        { 
            i++; 
            swap(&arr[i], &arr[j]); 
        } 
    } 
    swap(&arr[i + 1], &arr[high]); 
    return (i + 1); 
} 

void quickSort(int arr[], int low, int high) 
{ 
    if (low < high) 
    { 
        int pi = partition(arr, low, high);
        quickSort(arr, low, pi - 1); 
        quickSort(arr, pi + 1, high); 
    } 
} 

void printArray(int arr[], int size) 
{ 
    int i; 
    for (i = 0; i < size; i++) 
        cout << arr[i] << " "; 
    cout << endl; 
} 
  
int main() 
{ 
    int arr[] = {10, 7, 8, 9, 1, 5}; 
    int n = sizeof(arr) / sizeof(arr[0]); 
    quickSort(arr, 0, n - 1); 
    cout << "Sorted array: \n"; 
    printArray(arr, n); 
    return 0; 
} 
```



### The keywords:

In [49]:
import keyword
print(keyword.kwlist)

['False', 'None', 'True', 'and', 'as', 'assert', 'async', 'await', 'break', 'class', 'continue', 'def', 'del', 'elif', 'else', 'except', 'finally', 'for', 'from', 'global', 'if', 'import', 'in', 'is', 'lambda', 'nonlocal', 'not', 'or', 'pass', 'raise', 'return', 'try', 'while', 'with', 'yield']


# Basic data types

## <font color='green'><b> Numbers </b></font> 

* Integers and floats work as you would expect from other languages:

In [50]:
x = 3.2
print(x, type(x))

3.2 <class 'float'>


In [51]:
print(x + 1)   # Addition
print(x - 1)   # Subtraction
print(x * 2)   # Multiplication
print(x ** 2)  # Exponentiation

4.2
2.2
6.4
10.240000000000002


In [52]:
x += 1
print(x)
x *= 2
print(x)

4.2
8.4


In [53]:
y = 2.5

print(type(y))
print(y, y + 1, y * 2, y ** 2)

<class 'float'>
2.5 3.5 5.0 6.25


* Note that unlike many languages, Python does not have unary increment (x++) or decrement (x--) operators.

* Python also has built-in types for long integers and complex numbers; you can find all of the details in the [documentation](https://docs.python.org/3.7/library/stdtypes.html#numeric-types-int-float-long-complex).

## <font color='green'><b> Booleans </b></font> 

* Python implements all of the usual operators for Boolean logic, but uses **English words** rather than symbols (`&&`, `||`, etc.):

In [54]:
t, f = True, False
print(type(t))

<class 'bool'>


Now we let's look at the operations:

In [55]:
print(t and f) # Logical AND;
print(t or f)  # Logical OR;
print(not t)   # Logical NOT;
print(t != f)  # Logical XOR;

False
True
False
True


## <font color='green'><b> Strings </b></font> 


In [56]:
w1 = 'hello'   # String literals can use single quotes
w2 = "world"   # or double quotes; it does not matter
print(w1, len(w1))

hello 5


- String concatenation:

In [57]:
hw = w1 + ' ' + w2  # String concatenation
print(hw)

hello world


* String  **methods**:

In [58]:
s = "hello"
print(s.capitalize())  # Capitalize a string
print(s.upper())       # Convert a string to uppercase; prints "HELLO"
print(s.rjust(7))      # Right-justify a string, padding with spaces
print(s.center(7))     # Center a string, padding with spaces
print(s.replace('l', '(ell)'))  # Replace all instances of one substring with another
print('  world '.strip())  # Strip leading and trailing whitespace
s = s + " world"
print(s.split())

Hello
HELLO
  hello
 hello 
he(ell)(ell)o
world
['hello', 'world']


* You can find a list of all string methods in the [documentation](https://docs.python.org/3.7/library/stdtypes.html#string-methods).

### <font color="gray">- EXERCISE 1</font>

**Given the string 'hello', give two methods of producing the letter 'o' using indexing.**

In [59]:
s = 'hello'

#TO DO 

###  <font color="green">- EXERCISE 2</font>
**Given the string 'I hate programming', substitute hate with love**

In [60]:
s = 'I hate programming' 

print(s.replace('hate', 'love'))

I love programming


## <font color='green'><b> Containers </b></font>  

Python includes several built-in container types: **lists**, **dictionaries**, **sets**, and **tuples**.

### <font color='green'><b> Lists </b></font>  

* A **list** is the Python equivalent of an **array**, but is **resizeable** and can contain elements of **different types**:

In [61]:
xs = [3, 1, 2]   # Create a list
print('- List:', xs)
print('- Element 2:', xs[2])
print('- Last elem: ', xs[-1])     # Negative indices count from the end of the list; prints "2"

- List: [3, 1, 2]
- Element 2: 2
- Last elem:  2


In [62]:
xs[2] = 'foo'    # Lists can contain elements of different types

xs[0] = '0'
print(xs)

['0', 1, 'foo']


In [63]:
xs.append('bar') # Add a new element to the end of the list
print(xs)  

['0', 1, 'foo', 'bar']


In [64]:
x = xs.pop()     # Remove and return the last element of the list
print("Selected element: " , x)
print("Remaining elements in the list: ", xs)

Selected element:  bar
Remaining elements in the list:  ['0', 1, 'foo']


* we can define also a **list of lists**

In [65]:
x = [['a', 'b', 'c'], [1,2,[100, 200, 300]] , 0]

print(x[1][2][0])

100


#### <font color="green">- EXERCISE 3</font>

**Reassign 'hello' in this  list to say 'goodbye' instead:**

In [94]:
list1 = [1,2,3,4,'hello']
#print(list1)

list1.pop()
list1.append('goodbye')
print(list1)

[1, 2, 3, 4, 'goodbye']


#### - EXERCISE 4

**Similarly to EXERCISE 3, reassign 'hello' in this nested list to say 'goodbye' instead:**

In [121]:
list3 = [1,2,[3,4,'hello']]

list3[2].pop()
list3[2].append('goodbye')
print(list3)


[1, 2, [3, 4, 'goodbye']]


#### - EXERCISE 5

**Given the list below, pop the last element and print it**

In [1]:
list1 = ['Mark', 'Sue', 'Jack', 'Emma']
x = list1.pop()
print(x)

Emma


#### <font color='green'><b> Slicing </b></font>  

In addition to accessing list elements one at a time, Python provides concise syntax to access sublists; this is known as slicing:

In [136]:
nums = list(range(5))    # range is a built-in function that creates a list of integers
print(nums)         # Prints "[0, 1, 2, 3, 4]"
print(nums[2:4])    # Get a slice from index 2 to 4 (exclusive); prints "[2, 3]"
print(nums[2:])     # Get a slice from index 2 to the end; prints "[2, 3, 4]"
print(nums[:2])     # Get a slice from the start to index 2 (exclusive); prints "[0, 1]"
print(nums[:])      # Get a slice of the whole list; prints ["0, 1, 2, 3, 4]"
print(nums[:-1])    # Slice indices can be negative; prints ["0, 1, 2, 3]"
nums[2:4] = [8, 9] # Assign a new sublist to a slice
print(nums)         # Prints "[0, 1, 8, 9, 4]"

[0, 1, 2, 3, 4]
[2, 3]
[2, 3, 4]
[0, 1]
[0, 1, 2, 3, 4]
[0, 1, 2, 3]
[0, 1, 8, 9, 4]


#### <font color='green'><b> Loops </b></font>  


You can loop over the elements of a list like this:

In [137]:
animals = ['cat', 'dog', 'monkey']
for animal in animals:
  print(animal)

cat
dog
monkey


* The built-in `enumerate` function allows to access the index of each element within the body of a loop:

In [138]:
animals = ['cat', 'dog', 'monkey']
for idx, animal in enumerate(animals):
  print('#{}: {}'.format(idx + 1, animal))

#1: cat
#2: dog
#3: monkey


#### <font color="green">- EXERCISE 6</font>

**Given the statement `st`, use `for`, `.split()`, and `if` to print out only the words that start with 's':**

In [5]:
st = 'Print only the words that start with s in this sentence'

list = st.split()

for word in list:
    if word[0] == 's':
        print(word)

start
s
sentence


####  List comprehensions

* When programming, frequently we want to transform one type of data into another. As a simple example, consider the following code that computes square numbers:

In [140]:
nums = [0, 1, 2, 3, 4]
squares = []
for x in nums:
  squares.append(x ** 2)
print(squares)

[0, 1, 4, 9, 16]


* You can make this code simpler using a **list comprehension**:

In [141]:
nums = [0, 1, 2, 3, 4]
squares = [x ** 2 for x in nums]
print(squares)

[0, 1, 4, 9, 16]


* List comprehensions can also contain conditions:

In [142]:
nums = [0, 1, 2, 3, 4]
even_squares = [x ** 2 for x in nums if x % 2 == 0]
print(even_squares)

[0, 4, 16]


#### - EXERCISE 7

**Similarly to EXERCISE 6, given the statement `st`, use the list comprehensions to print out only the words that start with 'w':**

In [143]:
st = "what a wonderful world"

#TODO 

### Dictionaries

A dictionary stores **(key, value) pairs**, similar to a `Map` in Java or an object in Javascript. You can use it like this:

In [144]:
d = {'cat': 'cute', 'dog': 'furry'}  # Create a new dictionary with some data
print(d['cat'])       # Get an entry from a dictionary; prints "cute"
print('cat' in d)     # Check if a dictionary has a given key; prints "True"

cute
True


In [145]:
d['fish'] = 'wet'    # Set an entry in a dictionary
print(d['fish'])      # Prints "wet"

wet


In [146]:
print(d['monkey'])  # KeyError: 'monkey' not a key of d

KeyError: 'monkey'

In [ ]:
print(d.get('monkey', 'N/A'))  # Get an element with a default; prints "N/A"
print(d.get('fish', 'N/A'))    # Get an element with a default; prints "wet"

In [ ]:
del d['fish']        # Remove an element from a dictionary
print(d.get('fish', 'N/A')) # "fish" is no longer a key; prints "N/A"

You can find all you need to know about dictionaries in the [documentation](https://docs.python.org/3.7/library/stdtypes.html#dict).

* It is easy to iterate over the keys in a dictionary:

In [ ]:
d.items()

In [ ]:
d = {'person': 2, 'cat': 4, 'spider': 8}
for animal, legs in d.items():
    print('A {} has {} legs'.format(animal, legs))

* **Dictionary comprehensions**: These are similar to list comprehensions, but allow you to easily construct dictionaries. For example:

In [ ]:
nums = [0, 1, 2, 3, 4]
even_num_to_square = {x: x ** 2 for x in nums if x % 2 == 0}
print(even_num_to_square)

### Sets

* A set is an **unordered collection** of distinct elements. As a simple example, consider the following:

In [ ]:
animals = {'cat', 'dog'}
print('cat' in animals)   # Check if an element is in a set; prints "True"
print('fish' in animals)  # prints "False"


In [ ]:
animals.add('fish')      # Add an element to a set
print('fish' in animals)
print(len(animals))       # Number of elements in a set;

In [ ]:
animals.add('cat')       # Adding an element that is already in the set does nothing
print(len(animals))       
animals.remove('cat')    # Remove an element from a set
print(len(animals))       

* **Loops**: Iterating over a set has the same syntax as iterating over a list; however since sets are **unordered**, you cannot make assumptions about the order in which you visit the elements of the set:

In [ ]:
animals = {'cat', 'dog', 'fish'}
for idx, animal in enumerate(animals):
    print('#{}: {}'.format(idx + 1, animal))

* **Set comprehensions**: Like lists and dictionaries, we can easily construct sets using set comprehensions:

In [ ]:
from math import sqrt
print({int(sqrt(x)) for x in range(30)})

### Tuples

A tuple is an **(immutable) ordered list** of values. A tuple is in many ways similar to a list; one of the most important differences is that tuples can be used as keys in dictionaries and as elements of sets, while lists cannot. Here is a trivial example:

In [ ]:
d = {(x, x + 1): x for x in range(10)}  # Create a dictionary with tuple keys
t = (5, 6)       # Create a tuple
print(type(t))
print(d[t])       
print(d[(1, 2)])


In [ ]:
t[0] = 1 # ERROR: does not support item assignment!

## <font color='green'><b> Functions </b></font>  

* Python functions are defined using the `def` keyword. For example:

In [6]:
def sign(x):
  if x > 0:
    return 'positive'
  elif x < 0:
    return 'negative'
  else:
    return 'zero'

for x in [-1, 0, 1]:
  print(sign(x))
 

negative
zero
positive


We will often define functions to take **optional keyword arguments**, like this:

In [7]:
def hello(name, loud=False):
  if loud:
    print('HELLO, {}'.format(name.upper()))
  else:
    print('Hello, {}!'.format(name))

hello('Bob')
hello('Fred', loud=True)

Hello, Bob!
HELLO, FRED


#### <font color="green">- EXERCISE 8 </font>

**Write a function that checks and prints whether a number `num` is in a given range `[low, high]` (including the range extremes)**

In [18]:
def range_check(num, ran=[0,100]):
    if num >= low and num <= high:
        print('YES')
    else:
        print('NO')
    
    
# Call the range_Check function
low = 0
high = 100
r = [low, high]
num = 5
range_check(num, r) #num=5, low=2, high=7
range_check(5, [10,20])
range_check(30)

YES
YES
YES


#### <font color="green">- EXERCISE 9</font>

**Write a Python function to multiply all the numbers in a list.**

    Sample List : [1, 2, 3, -4]
    Expected Output : -24

In [31]:
def mult(list):
    p = 1
    for x in list:
        p *= x
        
    return(p)

list = [1,2,3,-4]
print(mult(list))

-24


## Classes 


A class is defined almost like a function, but using the class keyword, and the class definition usually contains a number of class method definitions (a function in a class).

Each class method should have an argument `self` as its first argument. This object is a self-reference.

Some class method names have special meaning, for example:

* `__init__`: The name of the method that is invoked when the object is first created.
* `__str__` : A method that is invoked when a simple string representation of the class is needed, as for example when printed.

The syntax for defining classes in Python is straightforward ([documentation](https://docs.python.org/3.7/tutorial/classes.html)):

In [ ]:
class Point:
  """
  Simple class for representing a point in a Cartesian coordinate system.
  """
  
  def __init__(self, x, y):
    """
    Create a new Point at x, y.
    """
    self.x = x
    self.y = y
    
  def translate(self, dx, dy):
    """
    Translate the point by dx and dy in the x and y direction.
    """
    self.x += dx
    self.y += dy
  
  def scale(self, s):
    self.x *= s
    self.y *= s
    
  def __str__(self):
    return("Point at [%f, %f]" % (self.x, self.y))

* To create a new instance of a class:

In [ ]:
p1 = Point(0, 0)  # this will invoke the __init__ method in the Point class
print(p1)         # this will invoke the __str__ method

* To invoke a class method in the class instance `p1`:

In [ ]:
p1.translate(0.25, 1.5)  # invoke method translate of p1

print(p1)

p2 = Point(1, 1)         # define a new Pointprint(p2)
print(p2)

p2.scale(3)
print(p2)


* **Class Variables vs. Class Instance Variables**: Class variables are variables shared across all instantiations of that class object--similar, for example, to static member variables in C#. In contrast, class instance variables are the more traditional member variables of a class.

In [ ]:
class Dog:

  kind = 'canine'          # class variable shared by all instances

  def __init__(self, name):
    self.name = name       # instance variable unique to each instance
        
d = Dog('Fido')
e = Dog('Buddy')
print(d.kind)                  # shared by all dogs
print(e.kind)                  # shared by all dogs
print(d.name)                  # unique to d
print(e.name)                  # unique to e

## Modules

**Modular programming**: The idea is to write functions and classes with a well-defined purpose and scope, and **reuse** these instead of repeating similar code in different part of a program (modular programming). 

Python supports modular programming at different levels. Functions and classes are examples of tools for low-level modular programming. Python modules are a higher-level modular programming construct, where we can collect related variables, functions and classes in a module. A python module is defined in a python file (with file-ending `.py`), and it can be made accessible to other Python modules and programs using the import statement.

Consider the following example: the file `mymodule.py` contains simple example implementations of a variable, function and a class:

In [ ]:
%%file mymodule.py
"""
Example of a python module. Contains a variable called my_variable,
a function called my_function, and a class called MyClass.
"""

my_variable = 0

def my_function():
  """ Example function """
  my_variable += 1
  return my_variable
    
class MyClass:
  """ Example class """

  def __init__(self):
    self.variable = my_variable
      
  def set_variable(self, new_value):
    """ Set self.variable to a new value
    """
    self.variable = new_value
      
  def get_variable(self):
    """ Return value"""
    return self.variable

We can import the module mymodule into our Python program using import:

In [ ]:
import MyClass from mymodule

c = MyClass()
print(c, '\n\n')

c.set_variable(10)
x = c.get_variable()
print(x, '\n\n')

help(mymodule) # to get a summary of what the module provides


### <font color='green'><b> - OTHER EXERCISES: </b></font>  

 



#### <font color='green'><b> Ex 1: </b></font>  


Write a Python program to print out all even numbers from a given numbers list in the same order and stop the printing if any numbers that come after 237 in the sequence.

In [ ]:
numbers = [386, 462, 47, 418, 907, 344, 236, 375, 823, 566, 597, 978, 328, 615, 953, 345, 
          399, 162, 758, 219, 918, 237, 412, 566, 826, 248, 866, 950, 626, 949, 687, 217, 
          815, 67, 104, 58, 512, 24, 892, 894, 767, 553, 81, 379, 843, 831, 445, 742, 717, 958,743, 527]

# put your code here...
 

#### <font color='green'><b> Ex 1.1: </b></font>  

 Find the position of an element x in the list `numbers`

In [ ]:
# TO DO

#### <font color='green'><b> Ex 2: </b></font>  


The Fibonacci sequence is a sequence in math that starts with 0 and 1, and then each successive entry is the sum of the previous two. Thus, the sequence goes 0,1,1,2,3,5,8,13,21,34,55,89,... Write a function that computes the Fibonacci sequence up to some number n

In [ ]:
#TO DO

#### <font color='green'><b> Ex 3: </b></font>  


Write a Python program to check whether a list contains a sublist.

In [ ]:
# TO DO

# <font color='green'><b> Numpy</b></font>  



* Numpy is the core library for scientific computing in Python. It provides a high-performance multidimensional array object, and tools for working with these arrays. 

* To use Numpy, we first need to import the `numpy` package:

In [44]:
import numpy as np

## <font color='green'><b> Arrays</b></font>  



* A numpy array is a **grid of values, all of the same type**, and is indexed by a tuple of nonnegative integers. The number of dimensions is the rank of the array; the shape of an array is a tuple of integers giving the size of the array along each dimension.

* We can initialize numpy arrays from nested Python lists, and access elements using square brackets:

In [43]:
import numpy as np

a = np.array([1, 2, 3])  # Create a rank 1 array
print(type(a), a.shape, a[0], a[1], a[2])
a[0] = 5                 # Change an element of the array
print(a)                  

ModuleNotFoundError: No module named 'numpy'

In [41]:
b = np.array([[1,2,3],[4,5,6]])   # Create a rank 2 array
print(b)

NameError: name 'np' is not defined

In [ ]:
print(b.shape)
print(b[0, 0], b[0, 1], b[1, 0])

Numpy also provides many functions to create arrays:

In [ ]:
a = np.zeros((2,2))  # Create an array of all zeros
print(a)

In [ ]:
b = np.ones((1,2))   # Create an array of all ones
print(b)

In [ ]:
c = np.full((2,2), 7) # Create a constant array
print(c)

In [ ]:
d = np.eye(2)        # Create a 2x2 identity matrix
print(d)

In [42]:
e = np.random.random((2,2)) # Create an array filled with random values
print(e)

NameError: name 'np' is not defined

#### <font color="green">- EXERCISE 10 </font>

**Create a vector of size 10, all null except for the fifth value which is 1 (hint: see `np.zeros`)**

In [46]:
a  = np.zeros((1,10))
a[0,4] = 1

print(a) 
 

[[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]]


### <font color="green">- EXERCISE 11</font>


**Create a 5x5 random matrix  and normalize it between 0 and 1**
* hint 1: use `np.random.randn()`,  `np.min()` and `np.max()`; 
* hint 2: to normalize a vector or a matrix implement the formula: $Znorm = \frac{Z - Zmin}{Zmax - Zmin}$)

In [66]:
def normalize(e):
    min = np.min(e)
    max = np.max(e)
    
    e = (e - min)/(max - min) 
            
    return e

e = np.random.random((5,5)) # Create an array filled with random values
#print(e)

print(e)
print('\n')

print(normalize(e))


 

UFuncTypeError: ufunc 'add' did not contain a loop with signature matching types (dtype('float64'), dtype('<U1')) -> None

###  Array indexing 



* Numpy offers several ways to index into arrays.

* **Slicing**: Similar to Python lists, numpy arrays can be sliced. Since arrays may be multidimensional, you must specify a slice for each dimension of the array:

In [ ]:
import numpy as np

# Create the following rank 2 array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

# Use slicing to pull out the subarray consisting of the first 2 rows
# and columns 1 and 2; b is the following array of shape (2, 2):
# [[2 3]
#  [6 7]]
b = a[:2, 1:3]
print(b)

* **ATTENTION**: A slice of an array is a view into the same data, so modifying it will modify the original array.

In [ ]:
print("Original value of array 'a[0,1]': " + str(a[0,1]))

b[0, 0] = 77    # b[0, 0] is the same piece of data as a[0, 1]
print("Final value of 'a[0,1]' after having modified 'b[0,0]': ': " + str(a[0,1]))


* You can also mix integer indexing with slice indexing. However, doing so will yield an array of lower rank than the original array. Note that this is quite different from the way that MATLAB handles array slicing:

In [ ]:
# Create the following rank 2 array with shape (3, 4)
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(a)

Two ways of accessing the data in the middle row of the array.
Mixing integer indexing with slices yields an array of lower rank,
while using only slices yields an array of the same rank as the
original array:

In [ ]:
row_r1 = a[1, :]    # Rank 1 view of the second row of a  
row_r2 = a[1:2, :]  # Rank 2 view of the second row of a
row_r3 = a[[1], :]  # Rank 2 view of the second row of a
print(row_r1, row_r1.shape)
print(row_r2, row_r2.shape)
print(row_r3, row_r3.shape)

In [ ]:
# We can make the same distinction when accessing columns of an array:
col_r1 = a[:, 1]
col_r2 = a[:, 1:2]
print(col_r1, col_r1.shape)
print()
print(col_r2, col_r2.shape)

* **Integer array indexing**: When you index into numpy arrays using slicing, the resulting array view will always be a subarray of the original array. In contrast, integer array indexing allows you to construct arbitrary arrays using the data from another array.

In [ ]:
a = np.array([[1,2], [3, 4], [5, 6]])
print(a)
# An example of integer array indexing.
# The returned array will have shape (3,) and 
print(a[[0, 1, 2], [0, 1, 0]])

# The above example of integer array indexing is equivalent to this:
print(np.array([a[0, 0], a[1, 1], a[2, 0]]))

In [ ]:
# When using integer array indexing, you can reuse the same
# element from the source array:
print(a[[0, 0], [1, 1]])

# Equivalent to the previous integer array indexing example
print(np.array([a[0, 1], a[0, 1]]))

* One useful trick with integer array indexing is selecting or mutating one element from each row of a matrix:

In [ ]:
# Create a new array from which we will select elements
a = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
print(a)

In [ ]:
# Create an array of indices
b = np.array([0, 2, 0, 1])

# Select one element from each row of a using the indices in b
print(a[np.arange(4), b])  # Prints "[ 1  6  7 11]"

In [ ]:
# Mutate one element from each row of a using the indices in b
a[np.arange(4), b] += 10
print(a)

* **Boolean array indexing**: Boolean array indexing lets you pick out arbitrary elements of an array. Frequently this type of indexing is used to select the elements of an array that satisfy some condition. Here is an example:

In [ ]:
a = np.array([[1,2], [3, 4], [5, 6]])

bool_idx = (a > 2)  # Find the elements of a that are bigger than 2;
                    # this returns a numpy array of Booleans of the same
                    # shape as a, where each slot of bool_idx tells
                    # whether that element of a is > 2.

print(bool_idx)

In [ ]:
# We use boolean array indexing to construct a rank 1 array
# consisting of the elements of a corresponding to the True values
# of bool_idx
print(a[bool_idx])

# We can do all of the above in a single concise statement:
print(a[a > 2])

### <font color="green">- EXERCISE 11</font>

**Given the array `a` make negatives all the odd numbers**

In [ ]:
a = np.array([[1,2], [3, 4], [5, 6]])

#TO DO 

### <font color="green">- EXERCISE 12</font>

**Create random vector of size 10 of integers within the range [1,100]  and replace the maximum value by 0**

In [ ]:
#TO DO 

### <font color="green">- EXERCISE 13</font>

**Create an array of random numbers according to the gaussian distribution (mu=0, std=1). Than find the value among these number that is the closest to `mu`.**

* hint 1 : see the function `np.random.normal`
* hint 2 : see the function `np.argmin()`


In [ ]:
#TO DO
 

### <font color='green'><b> Datatypes</b></font>  


* Every numpy array is a grid of elements of the same type. Numpy provides a large set of numeric datatypes that you can use to construct arrays. **Numpy tries to guess a datatype** when you create an array, but functions that construct arrays usually also include an **optional argument to explicitly specify the datatype**. Here is an example:

In [ ]:
import numpy as np

x = np.array([1, 2])  # Let numpy choose the datatype
y = np.array([1.0, 2.0])  # Let numpy choose the datatype
z = np.array([1, 2], dtype=np.int64)  # Force a particular datatype

print(x.dtype, y.dtype, z.dtype)

You can read all about numpy datatypes in the [documentation](http://docs.scipy.org/doc/numpy/reference/arrays.dtypes.html).

### <font color='green'><b> Array math</b></font>  
 

* Basic mathematical functions operate elementwise on arrays, and are available both as operator overloads and as functions in the numpy module:

In [ ]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

In [ ]:
# Elementwise sum; both produce the array
print(x + y)          # with operator
print(np.add(x, y))   # with numpy funcition

In [ ]:
# Elementwise difference; both produce the array
print(x - y)
print(np.subtract(x, y))

In [ ]:
# Elementwise product; both produce the array
print(x * y)
print(np.multiply(x, y))

In [ ]:
# Elementwise division; both produce the array
# [[ 0.2         0.33333333]
#  [ 0.42857143  0.5       ]]
print(x / y)
print(np.divide(x, y))

In [ ]:
# Elementwise square root; produces the array
# [[ 1.          1.41421356]
#  [ 1.73205081  2.        ]]
print(np.sqrt(x))

* Note that unlike MATLAB, `*` is elementwise multiplication, not matrix multiplication. We instead use the **dot function to compute inner products** of vectors, to multiply a vector by a matrix, and to multiply matrices. dot is available both as a function in the numpy module and as an instance method of array objects:

In [ ]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11, 12])

# Inner product of vectors; both produce 219
print(v.dot(w))
print(np.dot(v, w))

You can also use the `@` operator which is equivalent to numpy's `dot` operator.

In [ ]:
print(v @ w)

In [ ]:
# Matrix / vector product; both produce the rank 1 array [29 67]
print(x.dot(v))
print(np.dot(x, v))
print(x @ v)

In [ ]:
# Matrix / matrix product; both produce the rank 2 array
# [[19 22]
#  [43 50]]
print(x.dot(y))
print(np.dot(x, y))
print(x @ y)

* Numpy provides many useful functions for performing computations on arrays; one of the most useful is `sum`:

In [ ]:
x = np.array([[1,2],[3,4]])

print(np.sum(x))  # Compute sum of all elements; prints "10"
print(np.sum(x, axis=0))  # Compute sum of each column; prints "[4 6]"
print(np.sum(x, axis=1))  # Compute sum of each row; prints "[3 7]"

You can find the full list of mathematical functions provided by numpy in the [documentation](http://docs.scipy.org/doc/numpy/reference/routines.math.html).

Apart from computing mathematical functions using arrays, we frequently need to reshape or otherwise manipulate data in arrays. The simplest example of this type of operation is transposing a matrix; to transpose a matrix, simply use the T attribute of an array object:

In [ ]:
print(x)
print("transpose\n", x.T)

In [ ]:
v = np.array([[1,2,3]])
print(v )
print("transpose\n", v.T)

### Broadcasting

 

* Broadcasting is a powerful mechanism that allows numpy to **work with arrays of different shapes** when performing arithmetic operations. Frequently we have a smaller array and a larger array, and we want to use the smaller array multiple times to perform some operation on the larger array.

* For example, suppose that we want to add a constant vector to each row of a matrix. We could do it like this (_SOLUTION 1_):

In [ ]:
# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = np.empty_like(x)   # Create an empty matrix with the same shape as x

# Add the vector v to each row of the matrix x with an explicit loop
for i in range(4):
    y[i, :] = x[i, :] + v

print(y)

* This works; however when the matrix `x` is very large, computing an explicit loop in Python could be slow. Note that adding the vector v to each row of the matrix `x` is equivalent to forming a matrix `vv` by stacking multiple copies of `v` vertically, then performing elementwise summation of `x` and `vv`. We could implement this approach like this (_SOLUTION 2_):

In [ ]:
vv = np.tile(v, (4, 1))  # Stack 4 copies of v on top of each other
print(vv)                # Prints "[[1 0 1]
                         #          [1 0 1]
                         #          [1 0 1]
                         #          [1 0 1]]"

In [ ]:
y = x + vv  # Add x and vv elementwise
print(y)

* **_SOLUTION 3 with Broadcasting_** Numpy broadcasting allows us to perform this computation without actually creating multiple copies of v. Consider this version, using broadcasting:

In [ ]:
import numpy as np

# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = x + v  # Add v to each row of x using broadcasting
print(y)

The line `y = x + v` works even though `x` has shape `(4, 3)` and `v` has shape `(3,)` due to broadcasting; this line works as if v actually had shape `(4, 3)`, where each row was a copy of `v`, and the sum was performed elementwise.

Broadcasting two arrays together follows these rules:

1. If the arrays do not have the same rank, prepend the shape of the lower rank array with 1s until both shapes have the same length.
2. The two arrays are said to be compatible in a dimension if they have the same size in the dimension, or if one of the arrays has size 1 in that dimension.
3. The arrays can be broadcast together if they are compatible in all dimensions.
4. After broadcasting, each array behaves as if it had shape equal to the elementwise maximum of shapes of the two input arrays.
5. In any dimension where one array had size 1 and the other array had size greater than 1, the first array behaves as if it were copied along that dimension

If this explanation does not make sense, try reading the explanation from the [documentation](http://docs.scipy.org/doc/numpy/user/basics.broadcasting.html) or this [explanation](http://wiki.scipy.org/EricsBroadcastingDoc).

Functions that support broadcasting are known as universal functions. You can find the list of all universal functions in the [documentation](http://docs.scipy.org/doc/numpy/reference/ufuncs.html#available-ufuncs).

* Here are some applications of broadcasting:

In [ ]:
# Compute outer product of vectors
v = np.array([1,2,3])  # v has shape (3,)
w = np.array([4,5])    # w has shape (2,)

# we first reshape v to be a column vector of shape (3, 1)
v = np.reshape(v, (3, 1))
w = np.reshape(w, (1,2)) #not necessary indeed

print("Shape of 'v': ")
print(v.shape)

print("Shape of 'w': ")
print(w.shape)

# we can then broadcast it against w to yield
# an output of shape (3, 2), which is the outer product of v and w:

print(v * w)

In [ ]:
# Add a vector to each row of a matrix
x = np.array([[1,2,3], [4,5,6]])
v = np.array([1,2,3])  # v has shape (3,)
# x has shape (2, 3) and v has shape (3,) so they broadcast to (2, 3),
# giving the following matrix:

print(x + v)

In [ ]:
# Add a vector to each column of a matrix
# x has shape (2, 3) and w has shape (2,).
# If we transpose x then it has shape (3, 2) and can be broadcast
# against w to yield a result of shape (3, 2); transposing this result
# yields the final result of shape (2, 3) which is the matrix x with
# the vector w added to each column. Gives the following matrix:

print((x.T + w).T)

In [ ]:
# Another solution is to reshape w to be a row vector of shape (2, 1);
# we can then broadcast it directly against x to produce the same
# output.
print(x + np.reshape(w, (2, 1)))

In [ ]:
# Multiply a matrix by a constant:
# x has shape (2, 3). Numpy treats scalars as arrays of shape ();
# these can be broadcast together to shape (2, 3), producing the
# following array:
print(x * 2)

Broadcasting typically makes your code more concise and faster, so you should strive to use it where possible.

This brief overview has touched on many of the important things that you need to know about numpy, but is far from complete. Check out the [numpy reference](http://docs.scipy.org/doc/numpy/reference/) to find out much more about numpy.

### <font color='green'><b> - OTHER EXERCISES: </b></font>  
 

#### <font color='green'><b>Ex 1</b></font>  
 

Write a Python program to find a pair with highest product from a given array of integers.



In [ ]:
#TO DO 

#### <font color='green'><b> Ex 2</b></font>  
 
Write a NumPy program to test element-wise for complex number, real number of a given array `a`. Also test whether a given number is a scalar type or not.

In [ ]:
a = np.array([1+1j, 1+0j, 4.5, 3, 2, 2j])

#TO DO

#### <font color='green'><b> Ex 3</b></font>  
 
Write a NumPy program to create an array of 10 zeros, 10 ones, 10 fives and concatenate them.

In [ ]:
#TO DO

#### <font color='green'><b> Ex 4</b></font>  
 

Write a NumPy program to add a vector to each row of a given matrix.

In [ ]:
#TO DO

#### <font color='green'><b> Ex 5</b></font>  
 

Write a NumPy program to create a one dimensional array of forty pseudo-randomly generated values. Select random numbers from a uniform distribution between 0 and 1 and compute the histogram with 10 bins. (Hint: look at `numpy.random`)

In [ ]:
#TO DO

#### <font color='green'><b> Ex 6</b></font>  
 

Write a NumPy program to create a three-dimension array with shape `(2,3,4)` and entries the integer sequence: `1,2,3,..,24=2*3*4`.

In [ ]:
#TO DO

# <font color='green'><b> Matplotlib</b></font>  

* Matplotlib is a plotting library. In this section give a brief introduction to the `matplotlib.pyplot` module, which provides a plotting system similar to that of MATLAB.

In [ ]:
import matplotlib.pyplot as plt

By running this special iPython command, we will be displaying plots inline:

In [ ]:
%matplotlib inline

### <font color='green'><b> Plotting </b></font>  
 

The most important function in `matplotlib` is plot, which allows you to plot 2D data. Here is a simple example:

In [ ]:
import numpy as np

# Compute the x and y coordinates for points on a sine curve
x = np.arange(0, 3 * np.pi, 0.1)
y = np.sin(x)

# Plot the points using matplotlib
plt.plot(x, y)
plt.show()

With just a little bit of extra work we can easily plot multiple lines at once, and add a title, legend, and axis labels:

In [ ]:
y_sin = np.sin(x)
y_cos = np.cos(x)

# Plot the points using matplotlib
plt.plot(x, y_sin)
plt.plot(x, y_cos)
plt.xlabel('x axis label')
plt.ylabel('y axis label')
plt.title('Sine and Cosine')
plt.legend(['Sine', 'Cosine'])

### <font color="green">- EXERCISE 14</font>

Create two arrays `x1` and `x2` of values between 0 and 50. The first one must be of length 50 the second of length 1000 (hint: see function `np.linspace`). Evaluate the sin function (`np.sin()`) on this two arrays and store results in the arrays `y1` and `y2`. Create a plot where `x1` and `y1` are represented by blue circles, and `x2` and `y2` are represented by a dotted black line.  Label the symbols "sampled" and "continuous", and add a legend.  Adjust the y limits to suit your taste.

In [ ]:
#TO DO
 

### <font color='green'><b> Subplots</b></font>  

You can plot different things in the same figure using the subplot function. Here is an example:

In [ ]:
# Compute the x and y coordinates for points on sine and cosine curves
x = np.arange(0, 3 * np.pi, 0.1)
y_sin = np.sin(x)
y_cos = np.cos(x)

# Set up a subplot grid that has height 2 and width 1,
# and set the first such subplot as active.
plt.subplot(2, 1, 1)

# Make the first plot
plt.plot(x, y_sin)
plt.title('Sine')

# Set the second subplot as active, and make the second plot.
plt.subplot(2, 1, 2)
plt.plot(x, y_cos)
plt.title('Cosine')

# Show the figure.
plt.show()

You can read much more about the `subplot` function in the [documentation](http://matplotlib.org/api/pyplot_api.html#matplotlib.pyplot.subplot).

### <font color="green">- EXERCISE 14</font>

**Generate a vector `x` of 1000000 size of random normal distributed data ,and a vector `y` of the same size of random unifor distributed data. Plot their  histograms.**
* Hint: look at the `hist` function in matplotlib

In [ ]:
#TODO

